### ISSUE TITLE
envmode

### ISSUE THREAD

**Issue by bvandenbon** [bmeck/ssh-spawner#2]
Could you refer me to some documentation about the envMode setting.
I know this is value "inline", "cmd", or "default".

I tried to find more information about this, but couldn't find it.
I would like to execute my commands and capture events just as if it was a regular terminal command on the system itself. And while the command is running I need to send additional input (i.e. like confirmations). Does that work ? which mode should I use ?

**Comment by bmeck** [comment]
These are ways that environment settings are propagated to the remote `ssh` target process.

`inline` - converts the variables to be run in the remote shell but does not export them prior to running the target bin.
`cmd` - `exports` the variables in the remote shell prior to running the target bin. 
`default` - uses the current environment variables and tries to send them to the remote target via [SendEnv](https://linux.die.net/man/5/ssh_config), but the remote server must support this via AcceptEnv.

In general `inline` and `cmd` are going to have more support, but `default` is simpler for most commands.

**Comment by bvandenbon** [comment]
Thank you for your quick feedback. It's most appreciated.

I have to admit that most of that sounds like Chinese to me.
I have no idea what you mean by variables or the "target bin".

Assuming that all 3 of them are supported.
If response time is all what matters, would you prefer any of these 3
methods ?
Simple means fast ? --> go for the "default" ?

**Comment by bmeck** [comment]
yes, default
