### ISSUE TITLE
running multiple commands

### ISSUE THREAD

**Issue by bvandenbon** [bmeck/ssh-spawner#4]
any advice for running multiple commands ?
e.g. `wget "http://something" && mkdir directory && cd directory && wget "http://somethingelse"`

Am I correct that this kind of behavior is not supported ?

**Comment by objt-ba** [comment]
In the end I ended up transfering an sh file, and then executing the sh file.
Which does the trick for me.

**Comment by bvandenbon** [comment]
worked around it by specifying all commands in an `commands.sh` file and doing a `wget`, `chmod +x` and finally executing it, reducing it to connecting 3 times.
